"""Smoke and integration tests for data_prep.py, tiny_gpt.py and view_pt.py.

Runs on CPU in temporary folders (nothing in the project folder is written):
    python -m unittest -v test_tiny_gpt.py
"""

import glob
import hashlib
import io
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
import unittest
import unittest.mock
from contextlib import redirect_stdout

import numpy as np
import torch

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import data_prep  # noqa: E402
import tiny_gpt  # noqa: E402

PY = sys.executable
BIO = ("Genetic drift changes allele frequencies in small populations. Natural selection acts on phenotypes, "
       "and heritability measures additive genetic variance. Proteins are built from amino acids; DNA is "
       "transcribed into RNA. Genome-wide association studies test variants for disease.")
OFF = ("The football season began in autumn. The striker scored twice and the stadium cheered. "
       "Tickets for the next match sold out within an hour.")


def run(args, cwd=HERE, timeout=900):
    env = dict(os.environ, PYTHONIOENCODING="utf-8")
    proc = subprocess.run([PY] + args, cwd=cwd, capture_output=True, text=True, encoding="utf-8",
                          errors="replace", timeout=timeout, env=env)
    return proc.returncode, proc.stdout + proc.stderr


def paragraphs(seed, n=40):
    rng = np.random.default_rng(seed)
    words = ("gene allele protein cell membrane enzyme variance selection drift mutation population heritability "
             "regression likelihood matrix eigenvalue probability cohort biobank pathway receptor ligand dose "
             "pharmacology histology tissue sequencing chromosome locus haplotype linkage").split()
    out = []
    for _ in range(n):
        out.append(" ".join(rng.choice(words, size=int(rng.integers(12, 30)))).capitalize() + ".")
    return "\n\n".join(out)


class Corpus:
    """A small but messy corpus exercising every cleaning / filtering path."""

    def __init__(self, root):
        self.md = os.path.join(root, "md")
        os.makedirs(self.md)
        boiler = "Status: generated by the production pipeline for internal review only"
        for i in range(24):
            text = f"# Topic {i}\n\n{boiler}\n\n{BIO}\n\n{paragraphs(i)}\n\n```python\ndef f(x):\n    return x ** 2\n```\n\n| a | b |\n|---|---|\n| 1 | 2 |\n"
            with open(os.path.join(self.md, f"topic_{i:02d}.md"), "w", encoding="utf-8", newline="\n") as f:
                f.write(text)
        shutil.copy(os.path.join(self.md, "topic_03.md"), os.path.join(self.md, "copy_of_topic_03.md"))
        with open(os.path.join(self.md, "topic_05.md"), encoding="utf-8") as f:
            near = f.read().replace("Topic 5", "Topic five")
        with open(os.path.join(self.md, "near_topic_05.md"), "w", encoding="utf-8") as f:
            f.write(near + "\nOne extra closing sentence.\n")
        with open(os.path.join(self.md, "windows.md"), "wb") as f:
            f.write(b"\xef\xbb\xbf" + (BIO + "\r\n\r\n" + paragraphs(99)).replace("\n", "\r\n").encode())
        open(os.path.join(self.md, "empty.md"), "w").close()
        with open(os.path.join(self.md, "garbled.md"), "w", encoding="utf-8") as f:
            f.write(BIO + "\n\n" + "��� �� index ��\n" + paragraphs(7) + "\x0c\x01")
        with open(os.path.join(self.md, "long_book.md"), "w", encoding="utf-8") as f:
            f.write("\n\n".join(paragraphs(1000 + k) for k in range(12)))
        with open(os.path.join(self.md, "narration.lt.md"), "w", encoding="utf-8") as f:
            f.write("Lietuviškas tekstas. " * 50)
        # Hugging Face save_to_disk folder standing in for Wikipedia
        from datasets import Dataset
        rows = {"id": [], "url": [], "title": [], "text": []}
        for i in range(60):
            bio = i % 3 != 0
            rows["id"].append(str(i))
            rows["url"].append(f"https://example.org/{i}")
            rows["title"].append(f"{'Genetics' if bio else 'Football'} article {i}")
            rows["text"].append((BIO + "\n\n" + paragraphs(200 + i, 6)) if bio else (OFF + "\n\n" + OFF))
        self.wiki = os.path.join(root, "wiki")
        Dataset.from_dict(rows).save_to_disk(self.wiki)
        # Parquet shard standing in for FineWeb-Edu
        import pyarrow as pa
        import pyarrow.parquet as pq
        n = 30
        table = pa.table({"id": [f"w{i}" for i in range(n)],
                          "text": [(BIO + " " + paragraphs(300 + i, 4)) if i % 2 else OFF * 3 for i in range(n)],
                          "int_score": [i % 5 for i in range(n)]})
        self.parquet = os.path.join(root, "web.parquet")
        pq.write_table(table, self.parquet)
        # gzipped JSON Lines standing in for a peS2o shard
        import gzip
        self.pes2o = os.path.join(root, "pes2o.json.gz")
        with gzip.open(self.pes2o, "wt", encoding="utf-8") as f:
            for i in range(40):
                text = (BIO + " " + paragraphs(700 + i, 5)) if i % 2 else (OFF + " " + OFF + " " + OFF)
                f.write(json.dumps({"id": f"p{i}", "text": text, "source": "s2orc"}) + "\n")
        # a second, named text source (e.g. converted slides)
        self.notes = os.path.join(root, "notes")
        os.makedirs(self.notes)
        for i in range(8):
            with open(os.path.join(self.notes, f"note_{i}.md"), "w", encoding="utf-8") as f:
                f.write(f"# Lecture note {i}\n\n" + paragraphs(500 + i, 12))


def make_office_files(folder):
    """Minimal .pptx / .xlsx / GWAS / .html fixtures without extra packages."""
    import gzip
    import zipfile
    a = "http://schemas.openxmlformats.org/drawingml/2006/main"
    p = "http://schemas.openxmlformats.org/presentationml/2006/main"
    s = "http://schemas.openxmlformats.org/spreadsheetml/2006/main"
    r = "http://schemas.openxmlformats.org/officeDocument/2006/relationships"
    with zipfile.ZipFile(os.path.join(folder, "talk.pptx"), "w") as z:
        z.writestr("ppt/slides/slide1.xml", f'<p:sld xmlns:a="{a}" xmlns:p="{p}"><p:cSld><p:spTree><p:sp><p:nvSpPr>'
                   f'<p:cNvPr id="1" name="t"/><p:cNvSpPr/><p:nvPr><p:ph type="title"/></p:nvPr></p:nvSpPr><p:txBody>'
                   f'<a:p><a:r><a:t>Genetic drift</a:t></a:r></a:p></p:txBody></p:sp><p:sp><p:txBody><a:p><a:r>'
                   f'<a:t>Chance changes allele frequencies</a:t></a:r></a:p></p:txBody></p:sp></p:spTree></p:cSld></p:sld>')
    with zipfile.ZipFile(os.path.join(folder, "traits.xlsx"), "w") as z:
        z.writestr("xl/workbook.xml", f'<workbook xmlns="{s}" xmlns:r="{r}"><sheets><sheet name="h2" sheetId="1" '
                   f'r:id="rId1"/></sheets></workbook>')
        z.writestr("xl/_rels/workbook.xml.rels", '<Relationships xmlns="http://schemas.openxmlformats.org/package/'
                   '2006/relationships"><Relationship Id="rId1" Target="worksheets/sheet1.xml" Type="x"/></Relationships>')
        z.writestr("xl/sharedStrings.xml", f'<sst xmlns="{s}"><si><t>trait</t></si><si><t>height</t></si></sst>')
        z.writestr("xl/worksheets/sheet1.xml", f'<worksheet xmlns="{s}"><sheetData><row r="1"><c r="A1" t="s"><v>0</v>'
                   f'</c></row><row r="2"><c r="A2" t="s"><v>1</v></c><c r="B2"><v>0.8</v></c></row></sheetData></worksheet>')
    with gzip.open(os.path.join(folder, "gwas.tsv.gz"), "wt", encoding="utf-8") as f:
        f.write("SNP\tCHR\tBP\tBETA\tP\n")
        for i in range(500):
            f.write(f"rs{i}\t{1 + i % 22}\t{1000 * i}\t0.1\t{1e-10 if i in (5, 6) else 0.5}\n")
    with open(os.path.join(folder, "page.html"), "w", encoding="utf-8") as f:
        f.write("<html><script>var x=1;</script><body><h1>Heritability</h1><p>Twin studies.</p></body></html>")
    open(os.path.join(folder, "figure.png"), "wb").close()


class TestPipeline(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.tmp = tempfile.mkdtemp(prefix="tiny_gpt_test_")
        cls.corpus = Corpus(cls.tmp)
        cls.ds = os.path.join(cls.tmp, "dataset")
        with redirect_stdout(io.StringIO()) as buf:
            data_prep.prepare(["--out", cls.ds, "--md-dir", cls.corpus.md, "--md-dir", f"notes={cls.corpus.notes}",
                               "--tokenizer-weights", "md=3", "--wiki-dir", cls.corpus.wiki,
                               "--jsonl", cls.corpus.pes2o, "--jsonl-name", "pes2o",
                               "--wiki-max-docs", "30", "--parquet", cls.corpus.parquet, "--parquet-name", "web",
                               "--min-score", "2", "--include-keywords", "genetic*,allele*,protein,DNA,RNA,genome*",
                               "--keyword-min-distinct", "2", "--vocab-size", "700", "--val-fraction", "0.2",
                               "--max-doc-chars", "4000", "--boilerplate-min-docs", "20", "--threads", "2"])
        cls.prep_log = buf.getvalue()
        cls.runs = os.path.join(cls.tmp, "runs")
        os.makedirs(cls.runs)
        cls.common = ["tiny_gpt.py", "--dataset", cls.ds, "--out-dir", cls.runs, "--log-file",
                      os.path.join(cls.runs, "log.txt"), "--device", "cpu", "--d-model", "64", "--layers", "2",
                      "--heads", "4", "--kv-heads", "2", "--ctx", "64", "--batch-size", "8", "--grad-accum", "1",
                      "--eval-every", "8", "--eval-tokens", "2048", "--save-every", "1000", "--sample-tokens", "8",
                      "--dropout", "0.1", "--tariff", "25"]

    @classmethod
    def tearDownClass(cls):
        shutil.rmtree(cls.tmp, ignore_errors=True)

    # ---------------- data preparation ----------------
    def read_docs(self):
        with open(os.path.join(self.ds, "docs.tsv"), encoding="utf-8") as f:
            header = f.readline().rstrip("\n").split("\t")
            return [dict(zip(header, line.rstrip("\n").split("\t"))) for line in f]

    def test_manifest_and_files(self):
        manifest, arrays = data_prep.open_token_files(self.ds, verify=True)
        self.assertEqual(manifest["format"], "tiny_gpt_dataset")
        self.assertEqual(set(manifest["sources"]), {"md", "notes", "wiki", "web", "pes2o"})
        pes2o = manifest["sources"]["pes2o"]
        self.assertEqual(pes2o["kept_docs"], 20, "the 20 biology records pass the keyword filter")
        self.assertEqual(pes2o["skipped"].get("keyword_min_hits"), 20)
        self.assertEqual(manifest["tokenizer"]["sample_weights"]["md"], 3.0)
        self.assertEqual(manifest["sources"]["notes"]["kind"], "markdown")
        for split in ("train", "val"):
            for name, arr in arrays[split].items():
                self.assertEqual(len(arr), manifest["sources"][name][split]["tokens"])
        self.assertTrue(os.path.isfile(os.path.join(self.ds, "report.md")))
        self.assertFalse(os.path.exists(os.path.join(self.ds, "_work")), "work spool must be removed")

    def test_cleaning_and_skips_are_recorded(self):
        docs = self.read_docs()
        by_id = {(d["source"], d["doc_id"]): d for d in docs}
        self.assertEqual(by_id[("md", "empty.md")]["reason"], "empty")
        self.assertEqual(by_id[("md", "narration.lt.md")]["reason"], "not_english")
        pair = [by_id[("md", "copy_of_topic_03.md")]["reason"], by_id[("md", "topic_03.md")]["reason"]]
        self.assertEqual(sorted(pair), ["", "exact_duplicate"], "exactly one copy kept, the later one skipped")
        self.assertIn(by_id[("md", "garbled.md")]["status"], ("train", "val"))
        m = json.load(open(os.path.join(self.ds, "manifest.json"), encoding="utf-8"))
        cleaning = m["sources"]["md"]["cleaning"]
        self.assertGreaterEqual(cleaning.get("replacement_lines_removed", 0), 1)
        self.assertGreaterEqual(cleaning.get("bom_removed", 0), 1)
        self.assertGreaterEqual(cleaning.get("newlines_normalised_docs", 0), 1)
        self.assertGreaterEqual(cleaning.get("oversized_docs_split", 0), 1)
        with open(os.path.join(self.ds, "boilerplate.tsv"), encoding="utf-8") as f:
            self.assertIn("generated by the production pipeline", f.read())

    def test_keyword_and_score_filters(self):
        m = json.load(open(os.path.join(self.ds, "manifest.json"), encoding="utf-8"))
        wiki = m["sources"]["wiki"]
        # 40 genetics articles pass the filter, 20 football ones do not; --wiki-max-docs 30 keeps the 30
        # best-ranked and records the other 10
        self.assertEqual(wiki["skipped"].get("keyword_min_hits", 0), 20)
        self.assertEqual(wiki["kept_docs"], 30)
        self.assertEqual(wiki["skipped"].get("over_max_docs_by_rank", 0), 10)
        web = m["sources"]["web"]
        self.assertGreater(web["skipped"].get("score_below_min", 0), 0)
        kept_titles = [d["title"] for d in self.read_docs() if d["source"] == "wiki" and d["status"] in ("train", "val")]
        self.assertTrue(all(t.startswith("Genetics") for t in kept_titles))

    def test_split_by_group_no_leakage(self):
        groups = {}
        for d in self.read_docs():
            if d["status"] in ("train", "val"):
                groups.setdefault(d["group"], set()).add(d["status"])
        self.assertTrue(all(len(s) == 1 for s in groups.values()), "a group straddles train/val")
        near = [d for d in self.read_docs() if d["doc_id"] in ("topic_05.md", "near_topic_05.md")]
        self.assertEqual(len({d["group"] for d in near}), 1, "near duplicates must share a group")
        self.assertEqual(len({d["status"] for d in near}), 1)

    def test_tokenizer_roundtrip(self):
        manifest = data_prep.read_manifest(self.ds)
        tok = data_prep.Tokenizer.from_file(os.path.join(self.ds, "tokenizer.model"), "lines")
        self.assertEqual(tok.vocab_size, manifest["tokenizer"]["vocab_size"])
        self.assertGreaterEqual(tok.bos_id, 0)
        self.assertGreaterEqual(tok.eos_id, 0)
        for text in ("def f(x):\n    return x ** 2\n", "| a |    b |\n|---|---|", "Gene\n\nDrift  twice",
                     "h² = 0.5 ± 0.1; 家", "  leading spaces"):
            self.assertEqual(tok.decode(tok.encode(text)), text)
        reloaded = data_prep.Tokenizer(tok.proto, "lines")
        self.assertEqual(reloaded.encode("Genetic drift"), tok.encode("Genetic drift"))

    def test_incomplete_build_is_rebuilt_not_refused(self):
        out = os.path.join(self.tmp, "partial")
        os.makedirs(os.path.join(out, "_work"))
        open(os.path.join(out, "train.md.bin"), "wb").close()
        self.assertTrue(data_prep._is_incomplete_build(out))
        open(os.path.join(out, "my_notes.txt"), "w").close()
        self.assertFalse(data_prep._is_incomplete_build(out), "foreign files must never be deleted")
        os.remove(os.path.join(out, "my_notes.txt"))
        open(os.path.join(out, "report.md"), "w").close()
        self.assertFalse(data_prep._is_incomplete_build(out), "a scan-only report is kept")

    # ---------------- model ----------------
    def test_model_forward_backward_and_gqa_paths(self):
        cfg = tiny_gpt.ModelConfig(vocab_size=100, ctx=16, d_model=32, n_layers=2, n_heads=4, n_kv_heads=2)
        torch.manual_seed(0)
        model = tiny_gpt.TinyGPT(cfg)
        x = torch.randint(0, 100, (3, 16))
        logits = model(x)
        self.assertEqual(tuple(logits.shape), (3, 16, 100))
        logits.float().mean().backward()
        self.assertTrue(all(p.grad is not None for p in model.parameters()))
        self.assertIs(model.lm_head.weight, model.token_embedding.weight)
        if tiny_gpt._enable_gqa_supported():
            model.eval()
            model.set_attention_impl("repeat_kv")
            a = model(x)
            model.set_attention_impl("gqa_native")
            b = model(x)
            self.assertTrue(torch.allclose(a, b, atol=1e-5), "GQA implementations must agree")
        w = model.blocks[0].attn.attention_weights(model.blocks[0].attn_norm(model.token_embedding(x)), model.rope)
        self.assertTrue(torch.allclose(w.sum(-1), torch.ones_like(w.sum(-1)), atol=1e-5))
        self.assertEqual(float(w[0, 0, 0, 1:].sum()), 0.0, "attention must be causal")
        total, _ = model.param_counts()
        self.assertEqual(total, tiny_gpt.count_params(cfg)[0])

    def test_invalid_model_settings_fail_clearly(self):
        with self.assertRaises(SystemExit) as ctx:
            tiny_gpt.ModelConfig(vocab_size=100, d_model=30, n_heads=4)
        self.assertIn("not divisible", str(ctx.exception.code))
        with self.assertRaises(SystemExit):
            tiny_gpt.ModelConfig(vocab_size=100, d_model=32, n_heads=4, n_kv_heads=3)

    def test_wsd_schedule(self):
        s = tiny_gpt.LRSchedule("wsd", 100, 1e-3, 1e-4, 10, 0.2, "1-sqrt")
        self.assertAlmostEqual(s.lr_at(10), 1e-3)
        self.assertAlmostEqual(s.lr_at(5), 5e-4)
        self.assertAlmostEqual(s.lr_at(80), 1e-3)
        self.assertAlmostEqual(s.lr_at(100), 1e-4)
        self.assertLess(s.lr_at(90), 1e-3)
        self.assertEqual(s.phase(95), "decay")

    def test_planner_respects_data_budget(self):
        manifest = {"tokenizer": {"vocab_size": 8192},
                    "sources": {"md": {"train": {"tokens": 16_000_000}, "doc_tokens_percentiles": {"90": 3000}},
                                "wiki": {"train": {"tokens": 51_000_000}, "doc_tokens_percentiles": {"90": 2000}}}}
        # a fixed memory budget: the real one is 40% of free RAM, so a busy machine would fail the test
        fixed_budget = (4 * 2 ** 30, "4.0 GiB (test)")
        for extra in ([], ["--steps", "15000"]):
            args = tiny_gpt.parse_args(["--name", "x"] + extra)
            with unittest.mock.patch.object(tiny_gpt, "device_memory_budget", return_value=fixed_budget):
                cfg, settings, lines = tiny_gpt.plan_run(args, manifest, torch.device("cpu"), None)
            n, _ = tiny_gpt.count_params(cfg)
            epochs = settings["steps"] * settings["tokens_per_step"] / 67e6
            self.assertLessEqual(epochs, 4.0 + 1e-6, f"planner exceeded the epoch cap with {extra}")
            self.assertLessEqual(n * 20, 4 * 67e6, f"model too large for the data with {extra}")
            if extra:
                self.assertEqual(settings["steps"], 15000)

    # ---------------- training, resume, generation, logs ----------------
    def test_train_resume_generate_log_and_viewer(self):
        code, out = run(self.common + ["--name", "A", "--steps", "24"])
        self.assertEqual(code, 0, out)
        code, out_b = run(self.common + ["--name", "B", "--steps", "24", "--stop-after-steps", "16", "--no-probes"])
        self.assertEqual(code, 0, out_b)
        self.assertIn("Stopped after 16 steps", out_b)
        code, out_r = run(["tiny_gpt.py", "--name", "B", "--out-dir", self.runs, "--log-file",
                           os.path.join(self.runs, "log.txt"), "--device", "cpu", "--resume", "--eval-every", "8",
                           "--eval-tokens", "2048", "--sample-tokens", "8", "--no-probes"])
        self.assertEqual(code, 0, out_r)
        self.assertIn("RESUMED", out_r)

        def metrics(text):
            return {int(m.group(1)): (float(m.group(2)), float(m.group(3)), int(m.group(4)), m.group(5)) for m in
                    re.finditer(r"step +(\d+)/24 \| train ([\d.]+) \| val ([\d.]+) @(\d+).*?\| (NEW BEST.*|best .*)", text)}

        a, b = metrics(out), metrics(out_r)
        self.assertEqual(sorted(a), [8, 16, 24])
        for step, (tr, va, at, status) in a.items():
            self.assertEqual(at, step, "validation must be labelled with the step it was measured at")
        self.assertEqual(len({v[1] for v in a.values()}), 3, "validation must be re-measured at every evaluation")
        self.assertEqual(a[24][:2], b[24][:2], "resumed run must reproduce the uninterrupted run exactly")
        # NEW BEST exactly when validation improved on every earlier value
        best = float("inf")
        for step in sorted(a):
            improved = a[step][1] < best
            self.assertEqual(a[step][3].startswith("NEW BEST"), improved)
            best = min(best, a[step][1])
        lines = out.splitlines()
        for i, line in enumerate(lines):
            if re.match(r"step +(8|16|24)/24 \| train", line):
                self.assertTrue(lines[i + 1].lstrip().startswith("sample @"), "sample must follow the metrics line")
        # log file mirrors the terminal, with header and footer
        log = open(os.path.join(self.runs, "log.txt"), encoding="utf-8").read()
        for needle in ("RUN ", "model: ", "train: ", "schedule: ", "step     24/24", "completed", "RESUMED"):
            self.assertIn(needle, log)
        # refuse to overwrite an existing run
        code, out_x = run(self.common + ["--name", "A", "--steps", "24"])
        self.assertNotEqual(code, 0)
        self.assertIn("already exists", out_x)
        self.assertIn("already exists", open(os.path.join(self.runs, "log.txt"), encoding="utf-8").read())
        # no training state saved yet (e.g. the PC shut down): --resume continues from the best checkpoint
        code, out_c = run(self.common + ["--name", "C", "--steps", "24", "--stop-after-steps", "8", "--no-probes"])
        self.assertEqual(code, 0, out_c)
        os.remove(os.path.join(self.runs, "C.pt"))
        code, out_c = run(["tiny_gpt.py", "--name", "C", "--out-dir", self.runs, "--log-file",
                           os.path.join(self.runs, "log.txt"), "--device", "cpu", "--resume", "--eval-every", "8",
                           "--eval-tokens", "2048", "--sample-tokens", "8", "--no-probes"])
        self.assertEqual(code, 0, out_c)
        self.assertIn("RESUMED FROM", out_c)
        self.assertIn("step     24/24", out_c)
        c_ck = torch.load(os.path.join(self.runs, "C.pt"), map_location="cpu", weights_only=True)
        self.assertEqual((c_ck["step"], c_ck["checkpoint_type"]), (24, "training"))
        # checkpoints: safe loading, types, tied storage
        train_ck = torch.load(os.path.join(self.runs, "A.pt"), map_location="cpu", weights_only=True)
        best_ck = torch.load(os.path.join(self.runs, "A_best.pt"), map_location="cpu", weights_only=True)
        self.assertEqual(train_ck["checkpoint_type"], "training")
        self.assertIn("optimizer", train_ck)
        self.assertEqual(best_ck["checkpoint_type"], "inference")
        self.assertNotIn("optimizer", best_ck)
        self.assertEqual(train_ck["model"]["lm_head.weight"].data_ptr(),
                         train_ck["model"]["token_embedding.weight"].data_ptr())
        self.assertEqual(len(train_ck["metrics"]["history"]), 4, "baseline + 3 evaluations")
        with open(os.path.join(self.runs, "A_metrics.jsonl"), encoding="utf-8") as f:
            self.assertEqual(len(f.readlines()), 4)
        # generation from best and from an explicit checkpoint
        code, out_g = run(["tiny_gpt.py", "--name", "A", "--out-dir", self.runs, "--log-file",
                           os.path.join(self.runs, "log.txt"), "--device", "cpu", "--generate", "Genetic drift",
                           "--length", "12"])
        self.assertEqual(code, 0, out_g)
        self.assertIn("Genetic drift", out_g)
        # viewer on training and inference-only checkpoints
        for name, expect in (("A.pt", "optimizer: AdamW state"), ("A_best.pt", "none stored (inference-only")):
            png = os.path.join(self.runs, name + ".png")
            code, out_v = run(["view_pt.py", os.path.join(self.runs, name), "--plot", "--html", "--out", png,
                               "--dpi", "60"])
            self.assertEqual(code, 0, out_v)
            self.assertIn(expect, out_v)
            self.assertNotIn("panel failed", out_v)
            self.assertGreater(os.path.getsize(png), 50_000)
            self.assertTrue(os.path.isfile(os.path.splitext(png)[0] + "_embeddings.html"))
        # default dashboard name carries the step and a timestamp (never overwrites an earlier one)
        code, out_v = run(["view_pt.py", os.path.join(self.runs, "A_best.pt"), "--plot", "--dpi", "50", "--no-forward"])
        self.assertEqual(code, 0, out_v)
        self.assertTrue(os.path.isfile(os.path.join(self.runs, "A_best_dashboard.png")))
        # fact benchmark with per-category table and per-item CSV
        log = os.path.join(self.runs, "log.txt")
        code, out_b = run(["tiny_gpt.py", "--name", "A", "--out-dir", self.runs, "--log-file", log, "--device", "cpu",
                           "--benchmark"])
        self.assertEqual(code, 0, out_b)
        self.assertIn("overall:", out_b)
        self.assertIn("population genetics", out_b)
        self.assertTrue(glob.glob(os.path.join(self.runs, "A_best_benchmark_step24_*.csv")))
        # safetensors export: read back, generate from it, view it
        export = os.path.join(self.runs, "export")
        code, out_e = run(["tiny_gpt.py", "--name", "A", "--out-dir", self.runs, "--log-file", log, "--export", export])
        self.assertEqual(code, 0, out_e)
        self.assertIn("verified", out_e)
        tensors, meta = tiny_gpt.read_safetensors(os.path.join(export, "model.safetensors"))
        self.assertNotIn("lm_head.weight", tensors, "tied weight stored once")
        self.assertEqual(meta["format"], "tinyGPT")
        code, out_ge = run(["tiny_gpt.py", "--checkpoint", export, "--log-file", log, "--device", "cpu",
                            "--generate", "Genetic drift", "--length", "5"])
        self.assertEqual(code, 0, out_ge)
        code, out_ve = run(["view_pt.py", export, "--no-forward"])
        self.assertEqual(code, 0, out_ve)
        self.assertIn("format tinyGPT", out_ve)
        code, _ = run(["tiny_gpt.py", "--name", "A", "--out-dir", self.runs, "--log-file", log, "--export", export])
        self.assertNotEqual(code, 0, "export must refuse a non-empty folder")
        # bits per byte in the metrics line, and a permanent experiments table
        self.assertRegex(out, r"\| bpb \d+\.\d{3} \|")
        with open(os.path.join(self.runs, "experiments.csv"), encoding="utf-8-sig") as f:
            table = f.read()
        self.assertIn("training run", table)
        self.assertIn("benchmark", table)
        # continued pre-training: a new dataset with the same tokenizer, then --init-from the first model, with a
        # time budget (which must also apply to --init-from runs)
        ds2 = os.path.join(self.tmp, "dataset_more")
        with redirect_stdout(io.StringIO()):
            data_prep.prepare(["--out", ds2, "--md-dir", self.corpus.md, "--tokenizer-from", self.ds,
                               "--keep-split-from", self.ds, "--val-fraction", "0.3", "--seed", "99"])
        before = {(d["source"], d["doc_id"]): d["status"] for d in self.read_docs() if d["status"] in ("train", "val")}
        with open(os.path.join(ds2, "docs.tsv"), encoding="utf-8") as f:
            head = f.readline().rstrip("\n").split("\t")
            after = [dict(zip(head, line.rstrip("\n").split("\t"))) for line in f]
        shared = [d for d in after if (d["source"], d["doc_id"]) in before and d["status"] in ("train", "val")]
        self.assertGreater(len(shared), 10)
        for d in shared:  # a different seed would split differently: the earlier split must win
            self.assertEqual(d["status"], before[(d["source"], d["doc_id"])], d["doc_id"])
        code, out_i = run(["tiny_gpt.py", "--dataset", ds2, "--init-from", os.path.join(self.runs, "A_best.pt"),
                           "--name", "A_more", "--out-dir", self.runs, "--log-file", log, "--device", "cpu",
                           "--time-budget-hours", "0.01", "--batch-size", "8", "--grad-accum", "1",
                           "--eval-every", "4", "--eval-tokens", "1024", "--sample-tokens", "4", "--no-probes",
                           "--tariff", "25"])
        self.assertEqual(code, 0, out_i)
        self.assertIn("initialised from", out_i)
        self.assertIn("time budget 0.01 h", out_i)
        # energy and carbon: metrics line, run summary, table, and a checkpoint total that adds up across --resume
        self.assertRegex(out, r"\| \d+\.\d{2} kWh, [\d,]+ g CO2e, £\d+\.\d{2} \|")
        self.assertIn("whole run", out)
        self.assertIn("energy_kwh", table.splitlines()[0])
        self.assertIn("Earlier sessions of this run", out_r)
        b_ck = torch.load(os.path.join(self.runs, "B.pt"), map_location="cpu", weights_only=True)
        self.assertGreater(b_ck["energy"]["cpu"], 0)
        # paired document bootstrap between two checkpoints
        code, out_c = run(["compare_models.py", os.path.join(self.runs, "A_best.pt"), os.path.join(self.runs, "B.pt"),
                           "--docs", "4", "--reps", "200"])
        self.assertEqual(code, 0, out_c)
        self.assertIn("Verdict:", out_c)
        self.assertTrue(glob.glob(os.path.join(self.runs, "compare_A_best_vs_B_*.csv")))
        # watermark: detectable with the key, absent without it
        import detect_text
        model, tok, cfg, _ = tiny_gpt.load_for_inference(os.path.join(self.runs, "A_best.pt"))
        marked = tiny_gpt.generate(model, tok, "Genetic drift", 120, torch.device("cpu"),
                                   generator=torch.Generator().manual_seed(1), watermark=("k", 0.25, 4.0))
        plain = tiny_gpt.generate(model, tok, "Genetic drift", 120, torch.device("cpu"),
                                  generator=torch.Generator().manual_seed(1))
        z_marked = detect_text.watermark_z(tok.encode(marked), "k", cfg.vocab_size, 0.25)[0]
        z_plain = detect_text.watermark_z(tok.encode(plain), "k", cfg.vocab_size, 0.25)[0]
        self.assertGreater(z_marked, 4, (z_marked, z_plain))
        self.assertLess(z_plain, 3, (z_marked, z_plain))
        code, out_d = run(["detect_text.py", "Genetic drift is a random process.", "--checkpoint",
                           os.path.join(self.runs, "A_best.pt"), "--watermark-key", "k"])
        self.assertEqual(code, 0, out_d)
        self.assertIn("likelihood score", out_d)
        # supervised fine-tuning, preference tuning, asking
        examples = os.path.join(HERE, "finetune_examples")
        code, out_s = run(["finetune.py", "sft", "--base", os.path.join(self.runs, "A_best.pt"), "--data",
                           os.path.join(examples, "sft_examples.jsonl"), "--name", "A_sft", "--out-dir", self.runs,
                           "--epochs", "1", "--batch", "4", "--device", "cpu", "--log-file", log])
        self.assertEqual(code, 0, out_s)
        self.assertIn("held-out loss", out_s)
        code, out_p = run(["finetune.py", "dpo", "--base", os.path.join(self.runs, "A_sft.pt"), "--data",
                           os.path.join(examples, "dpo_examples.jsonl"), "--name", "A_dpo", "--out-dir", self.runs,
                           "--epochs", "1", "--batch", "4", "--device", "cpu", "--log-file", log])
        self.assertEqual(code, 0, out_p)
        self.assertIn("reward_accuracy", out_p)
        code, out_a = run(["finetune.py", "ask", "What is an allele?", "--checkpoint",
                           os.path.join(self.runs, "A_dpo.pt"), "--device", "cpu", "--log-file", log,
                           "--max-new-tokens", "10"])
        self.assertEqual(code, 0, out_a)
        ck = torch.load(os.path.join(self.runs, "A_dpo.pt"), map_location="cpu", weights_only=True)
        self.assertEqual(ck["finetune"]["method"], "dpo")

    def test_keyword_syntax(self):
        kw = data_prep.KeywordFilter(["=MET", "*mab", "genom*", "Hardy-Weinberg"], [], min_hits=1, min_distinct=1)
        self.assertEqual(kw.evaluate("", "we met at noon")[1], "keyword_min_hits", "=MET must be case-sensitive")
        keep, _, _, terms = kw.evaluate("", "MET signalling, adalimumab, genomics, Hardy–Weinberg")
        self.assertTrue(keep)
        self.assertEqual(set(terms), {"=MET", "*mab", "genom*", "Hardy-Weinberg"})
        import collections
        import pyarrow as pa
        import pyarrow.compute as pc
        # overlapping terms each count (as in the Python check), in any separator, with case-sensitive wildcards
        kw = data_prep.KeywordFilter(["=MET", "*mab", "genom*", "Hardy-Weinberg", "genetic drift", "genetic*",
                                      "drift", "=BRCA*", "β-cell", "Crohn's disease"], [], min_hits=1)
        texts = ["we met", "MET and adalimumab", "genetic drift and genetic drifts", "BRCA1 and brca1",
                 "a β-cell here", "Crohn’s disease", "Hardy–Weinberg / genomics"]
        re2 = sum(np.asarray(pc.count_substring_regex(pa.array(texts), pattern=p, ignore_case=True))
                  for p in kw.include_patterns)
        python = [sum(kw._include.count(t, collections.Counter()).values()) for t in texts]
        self.assertEqual(python, [0, 2, 4, 1, 1, 1, 2])
        self.assertEqual(re2.tolist(), python, "the C++ prefilter must count what the Python filter counts")
        self.assertGreater(len(data_prep.read_terms(os.path.join(HERE, "keywords_biology.txt") + ",extra term")), 500)

    def test_probe_formats_and_statistics(self):
        path = os.path.join(self.tmp, "probes.tsv")
        with open(path, "w", encoding="utf-8") as f:
            f.write("# comment\ngenetics\teasy\tGenes are made of\tDNA\tsugar|fat|salt\nOld prompt\tanswer\tx|y\n")
        probes = tiny_gpt.read_probes(path)
        self.assertEqual([p["category"] for p in probes], ["genetics", "general"])
        bench = tiny_gpt.read_probes(tiny_gpt.DEFAULT_PROBES)
        self.assertGreaterEqual(len(bench), 300)
        self.assertEqual(len({p["category"] for p in bench}), 16)
        self.assertTrue(all(len(p["distractors"]) == 3 for p in bench), "three near-miss distractors per item")
        self.assertTrue({p["difficulty"] for p in bench} <= {"easy", "medium", "hard"}, "labels come from calibration")
        low, high = tiny_gpt.wilson_interval(5, 10)
        self.assertLess(low, 0.5)
        self.assertGreater(high, 0.5)
        self.assertEqual(tiny_gpt.fmt_dur(35_400), "9h 50m")
        self.assertEqual(tiny_gpt.fmt_dur(125), "2m 05s")

    def test_compat_dataset_names_follow_settings(self):
        a = tiny_gpt.parse_args(["--data", self.corpus.md, "--wiki-articles", "30000"])
        b = tiny_gpt.parse_args(["--data", self.corpus.md, "--wiki-articles", "50000"])
        self.assertNotEqual(tiny_gpt.compat_dataset_dir(a), tiny_gpt.compat_dataset_dir(b))
        self.assertIn("wiki50000", tiny_gpt.compat_dataset_dir(b))

    def test_converter(self):
        src, out = os.path.join(self.tmp, "raw"), os.path.join(self.tmp, "converted")
        os.makedirs(src)
        make_office_files(src)
        with open(os.path.join(src, "script.py"), "w", encoding="utf-8") as f:
            f.write("def heritability(va, vp):\n    return va / vp\n")
        import pymupdf
        pdf = pymupdf.open()
        pdf.new_page().insert_text((72, 72), "Heritability is the share of variance explained by genes.")
        pdf.save(os.path.join(src, "one_page.pdf"))
        pdf.close()
        pdf = pymupdf.open()  # a plot page with thousands of vector paths, then an ordinary page
        page = pdf.new_page()
        page.insert_text((72, 60), "Figure 1. Posterior draws of the heritability.")
        shape = page.new_shape()
        for i in range(12000):
            x, y = 72 + (i * 37) % 450, 100 + (i * 53) % 600
            shape.draw_line((x, y), (x + 1.5, y + 1.5))
        shape.finish(width=0.3)
        shape.commit()
        pdf.new_page().insert_text((72, 72), "Linkage disequilibrium decays with recombination.")
        pdf.save(os.path.join(src, "plot_pages.pdf"))
        pdf.close()
        import docx
        document = docx.Document()
        document.add_heading("Heritability", 1)
        document.add_paragraph("Twin studies compare MZ and DZ twins.")
        table = document.add_table(rows=2, cols=2)
        table.cell(0, 0).text, table.cell(1, 0).text = "trait", "height"
        document.save(os.path.join(src, "notes.docx"))
        code, text = run(["convert_to_markdown.py", src, "--out", out, "--by-type", "--workers", "2"])
        self.assertEqual(code, 0, text)
        slides = open(os.path.join(out, "slides", "talk.md"), encoding="utf-8").read()
        self.assertIn("## Slide 1: Genetic drift", slides)
        self.assertIn("- Chance changes allele frequencies", slides)
        self.assertIn("| height | 0.8 |", open(os.path.join(out, "tables", "traits.md"), encoding="utf-8").read())
        gwas = open(os.path.join(out, "tables", "gwas.md"), encoding="utf-8").read()
        self.assertIn("500 genetic variants", gwas)
        self.assertIn("lambda GC", gwas)
        self.assertIn("2 variants reach genome-wide significance", gwas)
        docx_md = open(os.path.join(out, "articles", "notes.md"), encoding="utf-8").read()
        self.assertIn("# Heritability", docx_md)
        self.assertIn("| trait |", docx_md)
        html_md = open(os.path.join(out, "articles", "page.md"), encoding="utf-8").read()
        self.assertIn("Twin studies.", html_md)
        self.assertNotIn("var x", html_md)
        report = open(os.path.join(out, "conversion_report.tsv"), encoding="utf-8").read()
        self.assertIn("image: a text-only model cannot use pixels", report)
        self.assertTrue(os.path.isfile(os.path.join(out, "codes", "script.md")))
        self.assertTrue(os.path.isfile(os.path.join(out, "articles", "one_page.md")), "short PDFs are articles")
        plots = open(os.path.join(out, "articles", "plot_pages.md"), encoding="utf-8").read()
        self.assertIn("Posterior draws of the heritability", plots, "plot-heavy pages are read as plain text")
        self.assertIn("Linkage disequilibrium decays", plots)

    def test_llama_checkpoint_conversion_and_floor(self):
        """A Hugging Face Llama checkpoint (rotate-half RoPE layout) loads into TinyGPT
        with identical outputs; the shuffled-question floor is scored and deterministic."""
        import calibrate_probes
        cfg = tiny_gpt.ModelConfig(vocab_size=97, ctx=32, d_model=64, n_layers=2, n_heads=4, n_kv_heads=2)
        torch.manual_seed(0)
        ref = tiny_gpt.TinyGPT(cfg).eval()
        sd = ref.state_dict()

        def to_hf(w, heads):  # the permutation Hugging Face's Llama conversion applies
            out, inp = w.shape
            return w.reshape(heads, out // heads // 2, 2, inp).transpose(1, 2).reshape(out, inp)
        raw = {"model.embed_tokens.weight": sd["token_embedding.weight"], "model.norm.weight": sd["norm.weight"]}
        for i in range(cfg.n_layers):
            b, h = f"blocks.{i}.", f"model.layers.{i}."
            raw[h + "self_attn.q_proj.weight"] = to_hf(sd[b + "attn.q_proj.weight"], cfg.n_heads)
            raw[h + "self_attn.k_proj.weight"] = to_hf(sd[b + "attn.k_proj.weight"], cfg.n_kv_heads)
            for src, dst in (("self_attn.v_proj", "attn.v_proj"), ("self_attn.o_proj", "attn.o_proj"),
                             ("mlp.gate_proj", "ffn.gate"), ("mlp.up_proj", "ffn.up"), ("mlp.down_proj", "ffn.down"),
                             ("input_layernorm", "attn_norm"), ("post_attention_layernorm", "ffn_norm")):
                raw[h + src + ".weight"] = sd[b + dst + ".weight"]
        config = {"model_type": "llama", "vocab_size": 97, "hidden_size": 64, "num_hidden_layers": 2,
                  "num_attention_heads": 4, "num_key_value_heads": 2, "intermediate_size": cfg.ffn_hidden,
                  "rope_theta": cfg.rope_base, "rms_norm_eps": cfg.norm_eps, "tie_word_embeddings": True}
        model, _ = calibrate_probes.tinygpt_from_llama(config, raw, ctx=32)
        x = torch.randint(0, 97, (2, 20))
        with torch.no_grad():
            self.assertTrue(torch.allclose(model(x), ref(x), atol=1e-5), "converted model must match exactly")
        self.assertEqual(tiny_gpt.shuffled_prompt("a b c d e f", 1), tiny_gpt.shuffled_prompt("a b c d e f", 1))
        self.assertEqual(sorted(tiny_gpt.shuffled_prompt("a b c d e f", 2).split()), list("abcdef"))

    def test_data_prep_limits_ids_and_bytes(self):
        """--*-max-docs fills from documents actually kept, equal file names in two
        folders of one source stay distinct, document parts rejoin exactly, and
        byte_tables count exactly the bytes of the text (bits per byte)."""
        a, b = os.path.join(self.tmp, "fold_a"), os.path.join(self.tmp, "fold_b")
        for k, folder in enumerate((a, b)):
            os.makedirs(folder)
            with open(os.path.join(folder, "same.md"), "w", encoding="utf-8") as f:
                f.write(f"# Folder {k}\n\n" + BIO + "\n\n" + paragraphs(1200 + k, 8))
        out = os.path.join(self.tmp, "limits_dataset")
        with redirect_stdout(io.StringIO()):
            data_prep.prepare(["--out", out, "--md-dir", f"md={a}", "--md-dir", f"md={b}",
                               "--jsonl", self.corpus.pes2o, "--jsonl-name", "pes2o", "--jsonl-max-docs", "5",
                               "--parquet", self.corpus.parquet, "--parquet-name", "web", "--parquet-max-docs", "4",
                               "--include-keywords", "genetic*,allele*,protein,DNA,RNA,genome*",
                               "--keyword-sources", "PES2O,web", "--vocab-size", "600", "--val-fraction", "0.3"])
        m = data_prep.read_manifest(out)
        self.assertEqual(m["sources"]["pes2o"]["kept_docs"], 5)
        self.assertTrue(m["sources"]["pes2o"]["stopped_early"])
        self.assertEqual(m["sources"]["web"]["kept_docs"], 4)
        with open(os.path.join(out, "docs.tsv"), encoding="utf-8") as f:
            md_ids = sorted(line.split("\t")[1] for line in f if line.startswith("md\t"))
        self.assertEqual(md_ids, [os.path.join("fold_a", "same.md"), os.path.join("fold_b", "same.md")])
        tok = data_prep.load_tokenizer_from_any(self.ds)
        size, marked, line_break = tok.byte_tables()
        _, arrays = data_prep.open_token_files(self.ds)
        ids = np.concatenate([np.asarray(x, dtype=np.int64) for split in arrays.values() for x in split.values()])
        starts = np.nonzero(ids == tok.bos_id)[0].tolist() + [len(ids)]
        for s, e in zip(starts[:-1], starts[1:]):
            doc = ids[s:e]
            self.assertEqual(int(size[doc[1:]].sum() - (marked[doc[1:]] & line_break[doc[:-1]]).sum()),
                             len(tok.decode(doc).encode("utf-8")))
        text = "\n\n".join(paragraphs(1300 + k, 6) for k in range(6)) + "\nlast line"
        parts = data_prep.split_long_text(text, 1000)
        self.assertGreater(len(parts), 3)
        self.assertEqual(tok.decode([i for part in tok.encode_batch(parts) for i in part]), text)
        for extra, message in ((["--keyword-sources", "nosuch"], "unknown source"),
                               (["--md-dir", f"Books={a}", "--md-dir", f"books={b}"], "ignoring case")):
            with redirect_stdout(io.StringIO()), self.assertRaises(SystemExit) as ctx:
                data_prep.prepare(["--out", os.path.join(self.tmp, "refused"), "--md-dir", a] + extra)
            self.assertIn(message, str(ctx.exception.code))

    def test_parallel_workers_give_identical_datasets(self):
        """Documents checked in worker processes (from the first document on) give
        exactly the same dataset as the single-process build."""
        base = ["data_prep.py", "--md-dir", self.corpus.md, "--wiki-dir", self.corpus.wiki, "--wiki-max-docs", "30",
                "--parquet", self.corpus.parquet, "--parquet-name", "web", "--min-score", "2",
                "--parquet-max-docs", "4", "--jsonl", self.corpus.pes2o, "--jsonl-name", "pes2o", "--jsonl-max-docs", "6",
                "--include-keywords", "genetic*,allele*,protein,DNA,RNA,genome*", "--vocab-size", "700",
                "--val-fraction", "0.2", "--max-doc-chars", "4000"]
        prints = []
        for workers in ("1", "2"):
            out = os.path.join(self.tmp, f"parallel_{workers}")
            code, text = run(base + ["--out", out, "--workers", workers, "--worker-warmup", "0"])
            self.assertEqual(code, 0, text)
            if workers == "2":
                self.assertIn("worker processes", text)
            prints.append(data_prep.read_manifest(out)["fingerprint"])
        self.assertEqual(prints[0], prints[1])

    def test_converter_edge_cases(self):
        import pymupdf
        import convert_to_markdown as conv
        src, out = os.path.join(self.tmp, "edge_src"), os.path.join(self.tmp, "edge_out")
        for sub in ("p1", "p2"):
            os.makedirs(os.path.join(src, sub))
        # 1. name clashes: same file name in two folders, and notes.md next to notes.html
        for sub in ("p1", "p2"):
            with open(os.path.join(src, sub, "media.md"), "w", encoding="utf-8") as f:
                f.write(f"# Media {sub}\n\nText from {sub}.\n")
        with open(os.path.join(src, "notes.md"), "w", encoding="utf-8") as f:
            f.write("My own notes about heritability.\n")
        with open(os.path.join(src, "notes.html"), "w", encoding="utf-8") as f:
            f.write("<table><tr><td>height</td><td>0.8</td></tr></table><p>Twin studies of heritability.</p>")
        # 2. prose .txt whose first line has commas: copied whole, not cut to a table
        prose = "\n".join(f"Line {i}: drift, selection, and mutation shape variation." for i in range(400))
        with open(os.path.join(src, "prose.txt"), "w", encoding="utf-8") as f:
            f.write(prose + "\n")
        # 3. GWAS files the fast reader rejects (ragged row, '-' missing value), a -log10 p column, spaces
        rows = ["SNP\tCHR\tBP\tP\tBETA\tA1"] + [f"rs{i}\t1\t{i * 1000}\t0.5\t0.01\tA" for i in range(1, 400)]
        rows += ["rs9001\t2\t5000000\t1e-20\t0.3\tG", "rs9002\t2\t5500000\t1e-12\t0.2\tT", "rs9003\t3\t100\t-\t0.1",
                 "rs9004\t5\t9000000\t1e-400\t0.5\tC"]
        with open(os.path.join(src, "ragged.tsv"), "w", encoding="utf-8") as f:
            f.write("\n".join(rows) + "\n")
        with open(os.path.join(src, "neglog.tsv"), "w", encoding="utf-8") as f:
            f.write("CHR\tPOS\tLOG10P\n" + "\n".join(f"1\t{i * 10_000}\t0.30103" for i in range(1, 300))
                    + "\n4\t123456\t20\n")
        with open(os.path.join(src, "spaced.txt"), "w", encoding="utf-8") as f:
            f.write("CHR BP P\n" + "\n".join(f"1  {i * 100}  0.5" for i in range(1, 200)) + "\n7 777 3e-9\n")
        # 4. a notebook: markdown and code kept, outputs dropped
        with open(os.path.join(src, "analysis.ipynb"), "w", encoding="utf-8") as f:
            json.dump({"metadata": {"kernelspec": {"language": "python"}}, "cells": [
                {"cell_type": "markdown", "source": ["# Heritability\n", "Twin design."]},
                {"cell_type": "code", "source": "h2 = 2 * (0.8 - 0.5)",
                 "outputs": [{"data": {"image/png": "iVBORw0KGgo" * 50}}]}]}, f)
        code, text = run(["convert_to_markdown.py", src, "--out", out, "--recursive"])
        self.assertEqual(code, 0, text)
        made = sorted(os.listdir(out))
        self.assertIn("media.md", made)
        self.assertIn("media__p2.md", made, "both media.md inputs kept")
        self.assertIn("notes.md", made)
        self.assertIn("notes.html.md", made, "notes.html must not overwrite notes.md")
        self.assertEqual(open(os.path.join(out, "prose.md"), encoding="utf-8").read().strip(), prose)
        ragged = open(os.path.join(out, "ragged.md"), encoding="utf-8").read()
        self.assertIn("402 genetic variants", ragged)
        self.assertIn("3 variants reach genome-wide significance (p < 5e-8), forming 2 distinct loci", ragged,
                      "the two chr2 hits 0.5 Mb apart form one locus")
        self.assertIn("1.00e-20", ragged)
        self.assertIn("1.00e-400", ragged, "p-values below 1e-308 keep their exponent")
        self.assertIn("effect allele", ragged)
        neglog = open(os.path.join(out, "neglog.md"), encoding="utf-8").read()
        self.assertIn("lambda GC is 1.000", neglog)
        self.assertIn("1.00e-20", neglog)
        spaced = open(os.path.join(out, "spaced.md"), encoding="utf-8").read()
        self.assertIn("200 genetic variants", spaced)
        notebook = open(os.path.join(out, "analysis.md"), encoding="utf-8").read()
        self.assertIn("```python\nh2 = 2 * (0.8 - 0.5)\n```", notebook)
        self.assertNotIn("iVBOR", notebook)
        self.assertIn("height | 0.8", open(os.path.join(out, "notes.html.md"), encoding="utf-8").read())
        code, text = run(["convert_to_markdown.py", src, "--out", out, "--recursive"])
        self.assertIn("exists (use --overwrite)", open(os.path.join(out, "conversion_report.tsv"), encoding="utf-8").read())
        # 5. numbered labels at page edges survive; stepping page numbers and footers do not
        labels = [1, 1, 2, 3, 3, 4, 5, 5]  # a table can run over two pages: labels do not step like page numbers
        pages = [f"Supplementary Table {n}\nBody text {i} about linkage.\n\n{101 + i}" for i, n in enumerate(labels)]
        kept = "\n".join(conv.strip_page_furniture(pages))
        self.assertIn("Supplementary Table 5", kept)
        self.assertNotIn("\n105", "\n" + kept)
        # 6. a figure page with many separate shapes is read as plain text
        pdf = pymupdf.open()
        page = pdf.new_page()
        for i in range(800):
            page.draw_rect(pymupdf.Rect(20 + (i % 40) * 13, 40 + (i // 40) * 13, 30 + (i % 40) * 13,
                                        50 + (i // 40) * 13), fill=(0.2, 0.4, 0.8))
        self.assertTrue(conv._heavy_page(page))
        self.assertFalse(conv._heavy_page(pdf.new_page()))
        pdf.close()

    def test_pmc_jats_to_markdown(self):
        """PubMed Central XML becomes clean Markdown: sections, LaTeX equations,
        tables and captions kept; references, declarations and emails dropped."""
        import download_pmc
        xml = b"""<?xml version="1.0"?>
<pmc-articleset><article xml:lang="en" xmlns:mml="http://www.w3.org/1998/Math/MathML"
  xmlns:xlink="http://www.w3.org/1999/xlink">
<front><journal-meta><journal-title-group><journal-title>Genetics</journal-title></journal-title-group></journal-meta>
<article-meta><article-id pub-id-type="pmcid">PMC123</article-id>
<title-group><article-title>Drift in <italic>small</italic> populations</article-title></title-group>
<pub-date><year>2020</year></pub-date>
<permissions><license xlink:href="https://creativecommons.org/licenses/by/4.0/"><license-p>CC</license-p></license></permissions>
<abstract><p>Allele frequencies change by chance.</p></abstract></article-meta></front>
<body><sec><title>Introduction</title>
<p>Genetic drift was described by Wright<sup><xref ref-type="bibr" rid="b1">1</xref></sup>. The variance is
<inline-formula><mml:math><mml:msub><mml:mi>p</mml:mi><mml:mi>t</mml:mi></mml:msub></mml:math></inline-formula>, see below.
<disp-formula><alternatives><tex-math>\\documentclass{minimal}\\begin{document}}{}$$V = pq/2N$$\\end{document}</tex-math>
</alternatives></disp-formula> Contact: someone@example.org</p>
<list list-type="bullet"><list-item><p>small N</p></list-item><list-item><p>no selection</p></list-item></list>
<table-wrap><label>Table 1</label><caption><p>Effective sizes.</p></caption><table><thead><tr><th>Species</th><th>Ne</th></tr></thead>
<tbody><tr><td>Drosophila</td><td>10<sup>6</sup></td></tr></tbody></table></table-wrap>
<fig><label>Figure 1</label><caption><title>Fixation.</title><p>Most alleles are lost.</p></caption></fig>
<sec><title>A model</title><p>We model <mml:math><mml:mfrac><mml:mn>1</mml:mn><mml:mrow><mml:mn>2</mml:mn><mml:mi>N</mml:mi></mml:mrow></mml:mfrac></mml:math> per generation.</p></sec></sec>
<sec><title>Competing interests</title><p>None declared.</p></sec></body>
<back><ref-list><ref><mixed-citation>Wright S (1931) Evolution in Mendelian populations.</mixed-citation></ref></ref-list></back>
</article></pmc-articleset>"""
        import xml.etree.ElementTree as ET
        article = ET.fromstring(xml).find("article")
        self.assertEqual(download_pmc.article_pmcid(article), "PMC123")
        info, md = download_pmc.Jats(article).markdown()
        self.assertEqual((info["title"], info["journal"], info["year"], info["licence"]),
                         ("Drift in small populations", "Genetics", "2020", "CC BY 4.0"))
        for expected in ("# Drift in small populations", "## Abstract", "## Introduction", "### A model",
                         "described by Wright [1].", "$p_{t}$, see below.", "$$V = pq/2N$$", "- small N",
                         "Table 1. Effective sizes.", "| Species | Ne |", "| Drosophila | 10^6 |",
                         "Figure 1. Fixation. Most alleles are lost.", "$\\frac{1}{2N}$", "Contact: [email]"):
            self.assertIn(expected, md)
        for dropped in ("Competing interests", "None declared", "Mendelian populations", "someone@", "documentclass"):
            self.assertNotIn(dropped, md)

    def test_calibration_label_writer(self):
        import calibrate_probes
        path = os.path.join(self.tmp, "labels.tsv")
        with open(path, "w", encoding="utf-8") as f:
            f.write("# comment\ngenetics\tunrated\tGenes are made of\tDNA\tRNA|fat|salt\n"
                    "Cells are made of\tcells\tatoms|stars|rocks\n")
        calibrate_probes.rewrite_difficulties(path, ["easy", "hard"])
        probes = tiny_gpt.read_probes(path)
        self.assertEqual([(p["category"], p["difficulty"]) for p in probes], [("genetics", "easy"), ("general", "hard")])
        self.assertTrue(open(path, encoding="utf-8").read().startswith("# comment"))

    def test_page_furniture_is_stripped(self):
        import convert_to_markdown as conv
        pages = []
        for i in range(12):
            top = ["This electronic edition is for non-commercial purposes only.", f"{i + 1}",
                   "2. SINGLE-PARAMETER MODELS" if i % 2 else "2.1. ESTIMATING A PROBABILITY"]
            if i in (1, 5, 9):
                top.insert(0, "where")  # a real word that happens to start a page
            body = [f"Body text of page {i} about heritability and genetic drift." for _ in range(8)]
            bottom = [f"Nature | Vol 631 | 18 July 2024 | **{580 + i}**" if i % 2 else f"{580 + i} | Nature | Vol 631 | 18 July 2024"]
            if i in (0, 4, 8):
                bottom.append(f"Chapter {i // 4 + 1}")
            pages.append("\n".join(top + body + bottom))
        lines = "\n".join(conv.strip_page_furniture(pages)).splitlines()
        text = "\n".join(lines)
        for junk in ("non-commercial", "Nature | Vol 631", "SINGLE-PARAMETER MODELS", "ESTIMATING A PROBABILITY"):
            self.assertNotIn(junk, text)
        self.assertFalse([l for l in lines if l.strip().isdigit()], "page numbers are removed")
        self.assertEqual(lines.count("where"), 3, "ordinary words at a page edge are kept")
        for kept in ("Chapter 1", "Chapter 2", "Chapter 3", "Body text of page 7 about heritability and genetic drift."):
            self.assertIn(kept, lines)

    def test_text_root_and_language(self):
        root = os.path.join(self.tmp, "training_root")
        for folder in ("books", "articles", "wikipedia", "_private"):
            os.makedirs(os.path.join(root, folder))
        for folder in ("books", "articles", "_private"):
            for i in range(3):
                with open(os.path.join(root, folder, f"{folder}_{i}.md"), "w", encoding="utf-8") as f:
                    f.write(f"# {folder} {i}\n\n" + BIO + "\n\n" + paragraphs(900 + i, 10))
        out = os.path.join(self.tmp, "root_dataset")
        with redirect_stdout(io.StringIO()):
            data_prep.prepare(["--out", out, "--text-root", root, "--vocab-size", "600", "--val-fraction", "0.3"])
        self.assertEqual(set(data_prep.read_manifest(out)["sources"]), {"books", "articles"})
        self.assertTrue(data_prep.looks_english(BIO * 3))
        self.assertFalse(data_prep.looks_english("Genetinis dreifas yra atsitiktinis alel\u0173 da\u017eni\u0173 kitimas. " * 12))

    def test_unsafe_checkpoint_is_refused(self):
        class Payload:
            def __reduce__(self):
                return (print, ("UNSAFE CODE RAN",))

        path = os.path.join(self.tmp, "evil.pt")
        torch.save({"model": {}, "x": Payload()}, path)
        buf = io.StringIO()
        with redirect_stdout(buf), self.assertRaises(SystemExit) as ctx:
            tiny_gpt.safe_load(path)
        self.assertIn("Refusing to load", str(ctx.exception.code))
        self.assertNotIn("UNSAFE CODE RAN", buf.getvalue())

    def test_cli_rejects_bad_values(self):
        for bad in (["--name", "..\\evil"], ["--lr", "5"], ["--steps", "0"], ["--resume", "--init-from", "x.pt"]):
            with redirect_stdout(io.StringIO()), self.assertRaises(SystemExit):
                with open(os.devnull, "w") as devnull:
                    old = sys.stderr
                    sys.stderr = devnull
                    try:
                        tiny_gpt.parse_args(bad)
                    finally:
                        sys.stderr = old

    @unittest.skipUnless(os.path.isfile(os.path.join(HERE, "tiny_gpt_bpe_best.pt")), "no v3 checkpoint here")
    def test_legacy_v3_checkpoint_read_only(self):
        path = os.path.join(HERE, "tiny_gpt_bpe_best.pt")
        before = hashlib.sha256(open(path, "rb").read()).hexdigest()
        model, tok, cfg, obj = tiny_gpt.load_for_inference(path)
        self.assertEqual(tiny_gpt.checkpoint_info(obj), ("legacy-v3", "inference"))
        self.assertEqual(tok.encode_mode, "plain")
        self.assertEqual(cfg.ffn_hidden, (8 * cfg.d_model) // 3)
        text = tiny_gpt.generate(model, tok, "Genetic drift", 5, torch.device("cpu"),
                                 generator=torch.Generator().manual_seed(0))
        self.assertTrue(text.startswith("Genetic drift"))
        self.assertEqual(before, hashlib.sha256(open(path, "rb").read()).hexdigest())


if __name__ == "__main__":
    unittest.main(verbosity=2)
